{% set name = "daio" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daio-{{ version }}.tar.gz
  sha256: 677980ea470c66e22363553a8b3efb38cb53ae54025a5fed50ad65c1d12ed991

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - av <14
    - h5py
    - hdf5plugin

test:
  imports:
    - daio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/danionella/daio
  summary: video and data IO tools for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjudkewitz
