{% set name = "daio" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daio-{{ version }}.tar.gz
  sha256: 7c5340dbaafd2e357e1d9b30bc05e21fafbb3ab3e2c66b0484db4d30b5b5f895

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - av <14
    - h5py
    - hdf5plugin

test:
  imports:
    - daio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/danionella/daio
  summary: video and data IO tools for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjudkewitz
